### ISSUE TITLE
Help Installing

### ISSUE THREAD

**Issue by AntonJanHart** [bitshiftza/fnb-api#7]
Thank you and to all the contrabuters for this scipt.
I have been struggling for quite some time getting with this and I'm not sure how to get results.
If I run node-ts I get this:
```
ajhart@ubuntuvm:/var/www/html/fnb-api-master$ ts-node --project tsconfig.test.json ./test/index.ts
(node:31925) UnhandledPromiseRejectionWarning: TypeError: moment_1.default is not a function
    at Scraper.<anonymous> (/var/www/html/fnb-api-master/src/scrapers/scraper.js:231:62)
    at step (/var/www/html/fnb-api-master/src/scrapers/scraper.js:33:23)
    at Object.next (/var/www/html/fnb-api-master/src/scrapers/scraper.js:14:53)
    at fulfilled (/var/www/html/fnb-api-master/src/scrapers/scraper.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:31925) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31925) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When done compiling with tsc and add js to index.html to root directory:
```
<!DOCTYPE html>
<html>
<body>
<script>
const FnbApi = require('fnb-api').Api;
(async () => {
  const api = new FnbApi({
    username: 'xxxxx',
    password: 'xxxxx'
  });
  const accounts = await api.accounts.get();
  console.log(accounts);
  const detailedBalance = await accounts[0].detailedBalance();
  console.log(detailedBalance);
  const transactions = await accounts[0].transactions();
  console.log(transactions[0]);
  await api.close();
})();
</script>
</body>
</html>
```

I get console error in browser:
```
index.html:9 Uncaught ReferenceError: require is not defined
    at index.html:9
```

If I add <script src="dist/index.js"></script> to my index.html, I get Uncaught ReferenceError: exports is not defined
    at index.js:12

I'm not sure what to do here. Could you please provide instructions to get json results in console log.
Looking forward to your reply.

**Comment by AntonJanHart** [comment]
Finally got it to work, thank you very much.
